2020-11-04 21:06:51,240 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-04 21:06:59,968 INFO __main__ VS-uni-median ball_within_template 0 || loading data for generative training...
2020-11-04 21:08:45,618 INFO __main__ VS-uni-median ball_within_template 0 || training 'generative' models...
2020-11-04 21:08:48,741 INFO root training epoch 1...
2020-11-04 21:09:17,362 INFO root collecting auccess after epoch 1...
2020-11-04 21:09:24,891 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-04 21:09:26,557 ERROR __main__ Exception occured:
Traceback (most recent call last):
  File "solver.py", line 261, in <module>
    solver.train_supervised(epochs=epochs, train_mode=train_mode, test_ids = test_ids, setup=f'{eval_setup}_{fold_id}')
  File "/media/compute/homes/aharter/isy2020/phyre/flownet.py", line 1963, in train_supervised
    auccess = self.generative_auccess(test_ids, setup)
  File "/media/compute/homes/aharter/isy2020/phyre/flownet.py", line 897, in generative_auccess
    if self.radmode=="old":
AttributeError: 'FlownetSolver' object has no attribute 'radmode'
2020-11-04 21:23:40,862 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-04 21:23:46,818 INFO __main__ VS-uni-median ball_within_template 0 || loading data for generative training...
2020-11-04 21:25:30,598 INFO __main__ VS-uni-median ball_within_template 0 || training 'generative' models...
2020-11-04 21:25:33,683 INFO root training epoch 1...
2020-11-04 21:26:02,347 INFO root collecting auccess after epoch 1...
2020-11-04 21:26:09,323 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-04 21:26:10,955 ERROR __main__ Exception occured:
Traceback (most recent call last):
  File "solver.py", line 261, in <module>
    solver.train_supervised(epochs=epochs, train_mode=train_mode, test_ids = test_ids, setup=f'{eval_setup}_{fold_id}')
  File "/media/compute/homes/aharter/isy2020/phyre/flownet.py", line 1963, in train_supervised
    auccess = self.generative_auccess(test_ids, setup)
  File "/media/compute/homes/aharter/isy2020/phyre/flownet.py", line 897, in generative_auccess
    if self.radmode=="old":
AttributeError: 'FlownetSolver' object has no attribute 'radmode'
2020-11-04 22:17:59,194 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-04 22:18:05,113 INFO __main__ VS-uni-median ball_within_template 0 || loading data for generative training...
2020-11-04 22:19:46,982 INFO __main__ VS-uni-median ball_within_template 0 || training 'generative' models...
2020-11-04 22:19:49,705 INFO root training epoch 1...
2020-11-04 22:20:32,041 INFO root collecting auccess after epoch 1...
2020-11-04 22:20:38,984 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-04 22:20:40,721 ERROR __main__ Exception occured:
Traceback (most recent call last):
  File "solver.py", line 261, in <module>
    solver.train_supervised(epochs=epochs, train_mode=train_mode, test_ids = test_ids, setup=f'{eval_setup}_{fold_id}')
  File "/media/compute/homes/aharter/isy2020/phyre/flownet.py", line 1965, in train_supervised
    auccess = self.generative_auccess(test_ids, setup)
  File "/media/compute/homes/aharter/isy2020/phyre/flownet.py", line 907, in generative_auccess
    a  = sample_action_vector(ball, self.cache, uniform=self.uniform, radmode=self.radmode, mask=mask, check_border=True)
NameError: name 'sample_action_vector' is not defined
2020-11-04 22:32:55,274 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-04 22:33:02,818 INFO __main__ VS-uni-median ball_within_template 0 || loading data for generative training...
2020-11-04 22:34:44,423 INFO __main__ VS-uni-median ball_within_template 0 || training 'generative' models...
2020-11-04 22:34:47,512 INFO root training epoch 1...
2020-11-04 22:35:26,696 INFO root collecting auccess after epoch 1...
2020-11-04 22:35:34,016 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-04 22:35:35,671 ERROR __main__ Exception occured:
Traceback (most recent call last):
  File "solver.py", line 261, in <module>
    solver.train_supervised(epochs=epochs, train_mode=train_mode, test_ids = test_ids, setup=f'{eval_setup}_{fold_id}')
  File "/media/compute/homes/aharter/isy2020/phyre/flownet.py", line 1965, in train_supervised
    auccess = self.generative_auccess(test_ids, setup)
  File "/media/compute/homes/aharter/isy2020/phyre/flownet.py", line 907, in generative_auccess
    a  = sample_action_vector(ball, self.cache, uniform=self.uniform, radmode=self.radmode, mask=mask, check_border=True)
  File "/media/compute/homes/aharter/isy2020/phyre/phyre_utils.py", line 581, in sample_action_vector
    value = pic[ball].median()
RuntimeError: median cannot be called with empty tensor
2020-11-05 00:48:05,885 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 00:48:10,098 INFO __main__ VS-uni-median ball_within_template 0 || loading data for generative training...
2020-11-05 00:49:23,931 INFO __main__ VS-uni-median ball_within_template 0 || training 'generative' models...
2020-11-05 00:49:25,817 INFO root training epoch 1...
2020-11-05 00:49:47,398 INFO root collecting auccess after epoch 1...
2020-11-05 00:49:52,666 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 00:49:53,840 ERROR __main__ Exception occured:
Traceback (most recent call last):
  File "solver.py", line 261, in <module>
    solver.train_supervised(epochs=epochs, train_mode=train_mode, test_ids = test_ids, setup=f'{eval_setup}_{fold_id}')
  File "/media/compute/homes/aharter/isy2020/phyre/flownet.py", line 1965, in train_supervised
    auccess = self.generative_auccess(test_ids, setup)
  File "/media/compute/homes/aharter/isy2020/phyre/flownet.py", line 907, in generative_auccess
    a  = sample_action_vector(ball, self.cache, uniform=self.uniform, radmode=self.radmode, mask=mask, check_border=True)
  File "/media/compute/homes/aharter/isy2020/phyre/phyre_utils.py", line 581, in sample_action_vector
    value = pic[ball].median()
RuntimeError: median cannot be called with empty tensor
2020-11-05 09:13:34,403 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 09:13:38,584 INFO __main__ VS-uni-median ball_within_template 0 || loading data for generative training...
2020-11-05 09:14:53,992 INFO __main__ VS-uni-median ball_within_template 0 || training 'generative' models...
2020-11-05 09:14:55,877 INFO root training epoch 1...
2020-11-05 09:15:17,694 INFO root collecting auccess after epoch 1...
2020-11-05 09:15:22,789 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 09:21:45,170 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 09:21:49,334 INFO __main__ VS-uni-median ball_within_template 0 || loading data for generative training...
2020-11-05 09:23:03,356 INFO __main__ VS-uni-median ball_within_template 0 || training 'generative' models...
2020-11-05 09:23:05,239 INFO root training epoch 1...
2020-11-05 09:23:27,013 INFO root collecting auccess after epoch 1...
2020-11-05 09:23:32,233 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 09:23:33,397 ERROR __main__ Exception occured:
Traceback (most recent call last):
  File "solver.py", line 261, in <module>
    solver.train_supervised(epochs=epochs, train_mode=train_mode, test_ids = test_ids, setup=f'{eval_setup}_{fold_id}')
  File "/media/compute/homes/aharter/isy2020/phyre/flownet.py", line 1965, in train_supervised
    auccess = self.generative_auccess(test_ids, setup)
  File "/media/compute/homes/aharter/isy2020/phyre/flownet.py", line 907, in generative_auccess
    a  = sample_action_vector(ball, self.cache, uniform=self.uniform, radmode=self.radmode, mask=mask, check_border=True)
  File "/media/compute/homes/aharter/isy2020/phyre/phyre_utils.py", line 598, in sample_action_vector
    return np.array([x,y,rad/8])
TypeError: unsupported operand type(s) for /: 'tuple' and 'int'
2020-11-05 11:21:31,133 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 11:21:35,499 INFO __main__ VS-uni-median ball_within_template 0 || loading data for generative training...
2020-11-05 11:22:49,438 INFO __main__ VS-uni-median ball_within_template 0 || training 'generative' models...
2020-11-05 11:22:51,372 INFO root training epoch 1...
2020-11-05 11:23:10,828 INFO root collecting auccess after epoch 1...
2020-11-05 11:23:16,026 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 11:32:05,471 INFO root finish collecting auccess after epoch 1: 0.06666481159318015
2020-11-05 11:32:05,472 INFO root training epoch 2...
2020-11-05 11:32:26,179 INFO root collecting auccess after epoch 2...
2020-11-05 11:32:31,242 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 11:41:14,011 INFO root finish collecting auccess after epoch 2: 0.08710789207176282
2020-11-05 11:41:14,012 INFO root training epoch 3...
2020-11-05 11:41:32,948 INFO root training epoch 4...
2020-11-05 11:41:51,992 INFO root training epoch 5...
2020-11-05 11:42:12,056 INFO root collecting auccess after epoch 5...
2020-11-05 11:42:17,298 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 11:50:56,202 INFO root finish collecting auccess after epoch 5: 0.08463273838177493
2020-11-05 11:50:56,202 INFO root training epoch 6...
2020-11-05 11:51:15,595 INFO root training epoch 7...
2020-11-05 11:51:35,042 INFO root training epoch 8...
2020-11-05 11:51:54,485 INFO root training epoch 9...
2020-11-05 11:52:13,938 INFO root training epoch 10...
2020-11-05 11:52:33,368 INFO root collecting auccess after epoch 10...
2020-11-05 11:52:38,338 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
